images:
  tag: "prod"

ingress:
  host: chicorpbank.duckdns.org
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip

externalSecrets:
  awsSecretPath: /bank/prod/app

config:
  frontendOrigins: https://chicorpbank.duckdns.org
