images:
  userService: "replace-with-account.dkr.ecr.region.amazonaws.com/bank-user-service"
  transactionService: "replace-with-account.dkr.ecr.region.amazonaws.com/bank-transaction-service"
  activityService: "replace-with-account.dkr.ecr.region.amazonaws.com/bank-activity-service"
  frontend: "replace-with-account.dkr.ecr.region.amazonaws.com/bank-frontend"
  tag: "replace-with-approved-git-sha"

ingress:
  host: chicorpbank.duckdns.org
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip

externalSecrets:
  awsSecretPath: /bank/prod/app

config:
  frontendOrigins: https://chicorpbank.duckdns.org
  springJpaHibernateDdlAuto: validate
