apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 88.5.2
    helm:
      valuesObject:
        grafana:
          enabled: true
          persistence:
            enabled: false
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 384Mi
        alertmanager:
          enabled: true
          alertmanagerSpec:
            replicas: 1
            retention: 24h
            storage: {}
            resources:
              requests:
                cpu: 25m
                memory: 64Mi
              limits:
                cpu: 200m
                memory: 256Mi
        prometheus:
          enabled: true
          prometheusSpec:
            replicas: 1
            retention: 2d
            serviceMonitorSelectorNilUsesHelmValues: false
            ruleSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
            storageSpec: {}
            resources:
              requests:
                cpu: 200m
                memory: 512Mi
              limits:
                cpu: "1"
                memory: 1Gi
        kube-state-metrics:
          enabled: true
        prometheus-node-exporter:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: monitoring-prod-grafana
      jsonPointers:
        - /data/admin-password
    - group: apps
      kind: Deployment
      name: monitoring-prod-grafana
      jsonPointers:
        - /spec/template/metadata/annotations/checksum~1secret
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
