apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-config
  namespace: {{ .Values.namespace }}
data:
  FRONTEND_ORIGINS: {{ .Values.config.frontendOrigins | quote }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.config.kafkaBootstrapServers | quote }}
  REDIS_HOST: {{ .Values.config.redisHost | quote }}
  REDIS_PORT: {{ .Values.config.redisPort | quote }}
  SPRING_JPA_HIBERNATE_DDL_AUTO: {{ .Values.config.springJpaHibernateDdlAuto | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-frontend-config
  namespace: {{ .Values.namespace }}
data:
  config.js: |
    window.APP_CONFIG = {
      USER_API_URL: {{ .Values.frontendConfig.userApiUrl | quote }},
      TX_API_URL: {{ .Values.frontendConfig.transactionApiUrl | quote }},
      ACTIVITY_API_URL: {{ .Values.frontendConfig.activityApiUrl | quote }},
    };