apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: {{ .Values.namespace }}
  labels:
    app: user-service
    banking.techbleat.io/metrics: "true"
spec:
  selector:
    app: user-service
  ports:
    - name: http
      port: {{ .Values.service.userServicePort }}
      targetPort: {{ .Values.service.userServicePort }}
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: {{ .Values.namespace }}
  labels:
    app: transaction-service
    banking.techbleat.io/metrics: "transaction"
spec:
  selector:
    app: transaction-service
  ports:
    - name: http
      port: {{ .Values.service.transactionServicePort }}
      targetPort: {{ .Values.service.transactionServicePort }}
---
apiVersion: v1
kind: Service
metadata:
  name: activity-service
  namespace: {{ .Values.namespace }}
  labels:
    app: activity-service
    banking.techbleat.io/metrics: "true"
spec:
  selector:
    app: activity-service
  ports:
    - name: http
      port: {{ .Values.service.activityServicePort }}
      targetPort: {{ .Values.service.activityServicePort }}
---
apiVersion: v1
kind: Service
metadata:
  name: banking-frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: banking-frontend
spec:
  selector:
    app: banking-frontend
  ports:
    - name: http
      port: {{ .Values.service.frontendPort }}
      targetPort: {{ .Values.service.frontendPort }}
