images:
  userService: "replace-with-account.dkr.ecr.region.amazonaws.com/bank-user-service"
  transactionService: "replace-with-account.dkr.ecr.region.amazonaws.com/bank-transaction-service"
  activityService: "replace-with-account.dkr.ecr.region.amazonaws.com/bank-activity-service"
  frontend: "replace-with-account.dkr.ecr.region.amazonaws.com/bank-frontend"
  tag: "replace-with-git-sha"

ingress:
  host: banking.dev.internal
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip

externalSecrets:
  awsSecretPath: /bank/dev/app

config:
  frontendOrigins: https://banking.dev.internal
