images:
  userService: "716969407191.dkr.ecr.eu-west-2.amazonaws.com/bank-user-service"
  transactionService: "716969407191.dkr.ecr.eu-west-2.amazonaws.com/bank-transaction-service"
  activityService: "716969407191.dkr.ecr.eu-west-2.amazonaws.com/bank-activity-service"
  frontend: "716969407191.dkr.ecr.eu-west-2.amazonaws.com/bank-frontend"
  tag: "35940a809dfb3f9c2e2c87d56e747f34c9929f4d"

ingress:
  host: banking.dev.internal
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip

externalSecrets:
  awsSecretPath: arn:aws:secretsmanager:eu-west-2:716969407191:secret:rds!db-8ca613dd-664d-4719-9ab0-45556040ad8e-vP4MGr

config:
  frontendOrigins: https://banking.dev.internal

frontendConfig:
  userApiUrl: /api/usersvc
  transactionApiUrl: /api/txsvc
  activityApiUrl: /api/activitysvc